<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Actions_icon fa fa-star fa-fw</name>
   <tag></tag>
   <elementGuidId>d6dc96f2-4d8c-4908-bf1c-4390a88d3331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='discussion-list-61d404f60881a61d404f5cd62617']/table/tbody/tr/td/a/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-star fa-fw </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Unstar this discussion</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Unstar this discussion</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;discussion-list-61d404f60881a61d404f5cd62617&quot;)/table[@class=&quot;table discussion-list&quot;]/tbody[1]/tr[@class=&quot;discussion favourited subscribed&quot;]/td[@class=&quot;p-0 text-center align-middle icon-no-margin&quot;]/a[@class=&quot;btn btn-link&quot;]/span[@class=&quot;menu-action-text&quot;]/i[@class=&quot;icon fa fa-star fa-fw&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='discussion-list-61d404f60881a61d404f5cd62617']/table/tbody/tr/td/a/span/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/span/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='discussion-list-61d4034711e6661d40346d6c6e17']/table/tbody/tr/td/a/span/i</value>
   </webElementXpaths>
</WebElementEntity>
