<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_You can drag and drop files here to add_ebeecb</name>
   <tag></tag>
   <elementGuidId>66fca771-0261-4afe-b0da-a91b6d2fce7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dndupload-arrow</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'dndupload-arrow']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yui_3_17_2_1_1641269282999_64']/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dndupload-arrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1641269282999_64&quot;)/div[@class=&quot;fm-content-wrapper&quot;]/div[@class=&quot;fm-empty-container&quot;]/div[@class=&quot;dndupload-message&quot;]/div[@class=&quot;dndupload-arrow&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1641269282999_64']/div/div[2]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[4]/div/div[2]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
