<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Select log reader_chartjs-render-monitor</name>
   <tag></tag>
   <elementGuidId>140df7f0-19f0-47ad-bec9-ce4afa01ff7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.chartjs-render-monitor</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//canvas[@class = 'chartjs-render-monitor']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chart-area-61de2f0d7c8e161de2f0d6c35d16']/div/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>827</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>413</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chartjs-render-monitor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chart-area-61de2f0d7c8e161de2f0d6c35d16&quot;)/div[@class=&quot;chart-image&quot;]/canvas[@class=&quot;chartjs-render-monitor&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chart-area-61de2f0d7c8e161de2f0d6c35d16']/div/canvas</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
   </webElementXpaths>
</WebElementEntity>
